parameters:
#    chemin_du_son_site.example.class: CheminDuSon\SiteBundle\Example
    chemin_du_son.form.type.group.class: CheminDuSon\SiteBundle\Form\Type\GroupType
    chemin_du_son.form.type.concert.class: CheminDuSon\SiteBundle\Form\Type\ConcertType
    chemin_du_son.form.type.field.select2.class: CheminDuSon\SiteBundle\Form\Type\Field\Select2Type
    chemin_du_son.form.type.field.group.select.class: CheminDuSon\SiteBundle\Form\Type\Field\GroupSelectType

services:
    chemin_du_son_site.menu_builder:
        class: CheminDuSon\SiteBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory","@security.context"]

    chemin_du_son_site.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: chemin_du_son_site.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
    chemin_du_son_site.notification:
        class: CheminDuSon\SiteBundle\Services\NotificationService
        arguments: ["@session"]

    chemin_du_son.form.type.group:
        class: %chemin_du_son.form.type.group.class%
        tags:
            - { name: form.type, alias: group }

    chemin_du_son.form.type.concert:
        class: %chemin_du_son.form.type.concert.class%
        tags:
            - { name: form.type, alias: concert }
            - { name: form.type, alias: concert }

    chemin_du_son.form.type.field.select2:
        class: %chemin_du_son.form.type.field.select2.class%
        tags:
            - { name: form.type, alias: select2 }

    chemin_du_son.form.type.field.group.select:
        class: %chemin_du_son.form.type.field.group.select.class%
        tags:
            - { name: form.type, alias: group_select }