// Generated by CoffeeScript 1.6.3
(function() {
  var nav;

  nav = function() {
    return nav.prototype._init();
  };

  nav.prototype = {
    menuTriggerId: 'menu-trigger',
    siteWrapperId: 'site-wrapper',
    navigationMenuId: 'navigation-menu',
    menuOpenClass: 'menu-open',
    _init: function() {
      return this._initEvents();
    },
    _initEvents: function() {
      var menuTriggerElt, siteWrapperElt,
        _this = this;
      menuTriggerElt = document.getElementById(this.menuTriggerId);
      siteWrapperElt = document.getElementById(this.siteWrapperId);
      menuTriggerElt.addEventListener('click', function(ev) {
        ev.stopPropagation();
        ev.preventDefault();
        return _this._toggleMenu();
      });
      return $(document).click(function(event) {
        if (classie.has(siteWrapperElt, _this.menuOpenClass)) {
          return _this._toggleMenu();
        }
      });
    },
    _toggleMenu: function() {
      var siteWrapperElt;
      siteWrapperElt = document.getElementById(this.siteWrapperId);
      return classie.toggle(siteWrapperElt, this.menuOpenClass);
    }
  };

  nav();

}).call(this);
