// Generated by CoffeeScript 1.6.3
(function() {
  var nav;

  nav = function() {
    return nav.prototype._init();
  };

  nav.prototype = {
    menuTriggerId: 'menu-trigger',
    siteWrapperId: 'site-wrapper',
    navigationMenuId: 'navigation-menu',
    menuOpenClass: 'menu-open',
    _init: function() {
      return this._initEvents();
    },
    _initEvents: function() {
      var menuTriggerElt,
        _this = this;
      menuTriggerElt = document.getElementById(this.menuTriggerId);
      menuTriggerElt.addEventListener('click', function(ev) {
        var siteWrapperElt;
        ev.stopPropagation();
        ev.preventDefault();
        siteWrapperElt = document.getElementById(_this.siteWrapperId);
        return classie.toggle(siteWrapperElt, _this.menuOpenClass);
      });
      return $(document).click(function(event) {});
    }
  };

  nav();

}).call(this);
