parameters:
    # Assetic
    assetic.filter.compass.images_dir: %kernel.root_dir%/../web/images
    assetic.filter.compass.http_path:  /images

assetic:
    bundles: [ CheminDuSonSiteBundle, CheminDuSonUserBundle, FOSUserBundle ]
    filters:
        coffee:
            bin: /usr/local/bin/coffee
            node: /usr/local/bin/node
            apply_to: "\.coffee$"
        sass:
            bin: /home/clamzdev/.rvm/gems/ruby-2.1.1/bin/sass
        compass:
            bin: /home/clamzdev/.rvm/gems/ruby-2.1.1/bin/compass
            apply_to: "\.sass$"
            plugins: ["breakpoint", "susy"]
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: CheminDuSon\UserBundle\Entity\User
twig:
    form:
        resources:
            - 'CheminDuSonSiteBundle:Form:fields.html.twig'
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: CheminDuSonSiteBundle:Menu:knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
framework:
    templating:
        engines: ['haml','twig']

mt_haml:

fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    indexes:
        cds:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_french_analyzer:
                                type: custom
                                tokenizer: letter
                                filter: ["asciifolding", "lowercase", "french_stem", "stop_fr"]
                        filter:
                            stop_fr:
                                type: "stop"
                                stopwords: ["l", "m", "t", "qu", "n", "s", "j", "d"]
            types:
                Group:
                    mappings:
                        name : { analyzer: custom_french_analyzer }
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model:  CheminDuSon\SiteBundle\Entity\Group
                        provider: ~
                        listener: ~
                        finder: ~
                        repository: CheminDuSon\SiteBundle\Repository\Elastic\GroupElasticRepository
                Concert:
                    mappings: ~
                    persistence:
                        driver: orm
                        model:  CheminDuSon\SiteBundle\Entity\Concert
                        provider: ~
                        listener: ~