<?php

namespace CheminDuSon\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactDetailsRepository extends EntityRepository
{
}
